ruta: jdbc:mysql://dam2.mysql.iesquevedo.es:3335/SergioGarrido_Mensajitos?useSSL=false
user: root
password: quevedo2dam
driver: com.mysql.cj.jdbc.Driver
secretKey: codigolyoko
maximasLlamadas: 10
tiempoMaximoLlamadas: 20
tiempoLimpiarLlamadas: 30


